version: "3"
services:
  service-user:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="user-api","user-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - user_api_data:/data/postgres
    ports:
      - 5439:5432

  service-token:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="token-api","token-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - token_api_data:/data/postgres
    ports:
      - 5440:5432
  cache:
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  user_api_data: {}
  token_api_data: {}
  cache: {}
